# Generated by Django 5.0.4 on 2024-04-12 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore_management.book')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore_management.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='books',
            field=models.ManyToManyField(through='bookstore_management.CourseBook', to='bookstore_management.book'),
        ),
    ]
