# Generated by Django 5.0.4 on 2024-04-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_management', '0002_coursebook_course_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='books',
        ),
    ]
