# Generated by Django 5.0.4 on 2024-04-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_management', '0003_remove_course_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='books',
            field=models.ManyToManyField(through='bookstore_management.CourseBook', to='bookstore_management.book'),
        ),
    ]
